## Advance operation with Business examples

### Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
```python
    sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
```

In [20]:
import numpy as np

In [21]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==============Zomato sales data============")
print("sles data shape : ",sales_data.shape)
print("sample data for 1st to 3rd restorent: \n",sales_data[:3])

==============Zomato sales data============
sles data shape :  (5, 5)
sample data for 1st to 3rd restorent: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


axis = 0 for colmn wise &
axis = 1 for row wise

In [22]:
#total sales per year
print("Print without restoraunt id:\n",sales_data[:,1:])
print("Totel sales per yearly\n",np.sum(sales_data[:,1:],axis=0))

Print without restoraunt id:
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
Totel sales per yearly
 [ 810000  945000 1085000 1240000]


In [23]:
#minimum sale per restorent
print("minimum sale per restorent")
print(np.min(sales_data[:,1:],axis=1))

#maximum sale per year
print("maximum sale per year")
print(np.max(sales_data[:,1:],axis=0))

#average sale per restaurant
print("average sale per restaurant")
print(np.mean(sales_data[:,1:],axis=1)) #mean() return average

minimum sale per restorent
[150000 120000 200000 180000 160000]
maximum sale per year
[200000 230000 260000 300000]
average sale per restaurant
[200000. 152500. 247500. 225000. 195000.]


In [24]:
# Vector Operations
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])
print("Additions: ",vector1 + vector2)

print("Multiplications: ",vector1 * vector2)

print("dot product: ",np.dot(vector1,vector2))

angle = np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print("angle: ",angle)

Additions:  [ 7  9 11 13 15]
Multiplications:  [ 6 14 24 36 50]
dot product:  130
angle:  0.26554161733900966


In [25]:
#Vectorized
restaurant_types = np.array(['biryani', 'chinese', 'pizza', 'burger', 'cafe'])
vectorizedUpper = np.vectorize(str.upper) #from vectorize class we import and perform all python task
print("Vector in UpperCase: ",vectorizedUpper(restaurant_types))

Vector in UpperCase:  ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [26]:
month_avg = sales_data[:,1:]/12
print("Monthly Average Data:\n",month_avg)

Monthly Average Data:
 [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
