## Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ",arr[2:9])
print("Step : ",arr[1:9:2])
print("Negative Indexing : ",arr[-3])

Basic Slicing:  [3 4 5 6 7 8 9]
Step :  [2 4 6 8]
Negative Indexing :  8


In [3]:
array_2D = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print("Specific Element: ",array_2D[1,2]) #array[rowIndex,colomnIndex]
print("Entire Row",array_2D[0])  #array[rowIndex]
print("Entire Column : ",array_2D[:,2]) #array[colomnIndex]

Specific Element:  6
Entire Row [1 2 3]
Entire Column :  [3 6 9]


## Shorting

In [4]:
unsorted_arr = np.array([1,2,3,4,3,1,1,5,8,9,10,4])
print("Shorted arry: ",np.sort(unsorted_arr))

array_2d = np.array([[3,1],
                     [1,2],
                     [2,3]])
print("2D array Shorting: \n",np.sort(array_2d,axis=0)) #axis=0 means colmn wise sort
print("2D array Shorting: \n",np.sort(array_2d,axis=1)) #axis=1 row wise sort

Shorted arry:  [ 1  1  1  2  3  3  4  4  5  8  9 10]
2D array Shorting: 
 [[1 1]
 [2 2]
 [3 3]]
2D array Shorting: 
 [[1 3]
 [1 2]
 [2 3]]


### filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[ numbers%2==0 ] #this thing is called masking
#numbers % 2 == 0 => [False, True, False, True, False, True, False, True, False, True]
#NumPy filters and returns only the elements where the mask is True.
print("Even Numbers: ",even_numbers)

Even Numbers:  [ 2  4  6  8 10]


### mask and filter

In [6]:
mask = numbers>5  #we store expression for evolution we only use it with numpy
print("Numbers are N>5: ",numbers[mask])

Numbers are N>5:  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [7]:
indecies = [0,2,4]
print(numbers[indecies])

where_result = np.where(numbers>5)
print(where_result)  #return indexing of value in array
print("NP Where: ",numbers[where_result]) #get actual value

[1 3 5]
(array([5, 6, 7, 8, 9], dtype=int64),)
NP Where:  [ 6  7  8  9 10]


In [8]:
condition = np.where(numbers>5 ,numbers*2 ,numbers)
print(condition)
#advanced where condition used :
#where([condtition], if condition sutifised doit[***], else doit[***] )

[ 1  2  3  4  5 12 14 16 18 20]


In [9]:
#one more example of it:
condition = np.where(numbers>5 , True, False)
print(condition)

[False False False False False  True  True  True  True  True]


### Add and Remove

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_arr = np.concatenate((arr1,arr2)) #pass array in tuple // concatenate for add
print(combined_arr)

deleted = np.delete(combined_arr,1) #delete() for delete (array , index or (any,any,any))
print("after deletion array: ",deleted)

[1 2 3 4 5 6]
after deletion array:  [1 3 4 5 6]


### Array Compatbility 

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,2])

print("Compatibility Shape a with b: ",a.shape == b.shape)
print("Compatibility Shape b with c: ",b.shape == c.shape)
# Use when we need Element-wise Operation

Compatibility Shape a with b:  True
Compatibility Shape b with c:  False


In [12]:
#add new row in array -
original_arr = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_row_arr = np.vstack((original_arr,new_row)) #vstack() to add new row
print("with new row: ",with_row_arr)

#add new col in array -
new_col = np.array([[7],[8]])
with_col_arr = np.hstack((original_arr,new_col)) #hstack() to add new col
print("With new col: ",with_col_arr)

with new row:  [[1 2]
 [3 4]
 [5 6]]
With new col:  [[1 2 7]
 [3 4 8]]
