## Numpy arry and basic
Learn about array with Umesh

In [1]:
import numpy as np 

In [3]:
array_1d = np.array([1,2,3,4,5,6])
print("1D array: ",array_1d)

array_2d = np.array([[1,2,3],[4,5,6]])
print('2D array:',array_2d)

1D array:  [1 2 3 4 5 6]
2D array: [[1 2 3]
 [4 5 6]]


### List vs Numpy

In [6]:
pylist = [1,2,3]
#multiplication of pylist
print(pylist*2)

nparray = np.array([1,2,3])
#multiplication of nparray
print(nparray*2) #element wise multiplication run

#calculate time that consume
import time
start = time.time()
py_list = [i*99 for i in range(10000000)]
print('time taken by list: ',time.time()-start)

start = time.time()
py_arry = np.arange(10000000)*99
print('time taken by nparry: ',time.time()-start)


[1, 2, 3, 1, 2, 3]
[2 4 6]
time taken by list:  1.5463783740997314
time taken by nparry:  0.07628369331359863


### Creating array from scratch

In [16]:
zeros = np.zeros((3,4))
# zeros() method return zero's matrix 
#(number of rows, number of colomns)
print("zero's array:\n",zeros )

ones = np.ones((4,2))
#retun ones matrix
print("1's matrix\n",ones )


full = np.full((3,2),5)
#in full method full((matrix size parameter),value) using it we create a metrix and value of we set it 
#it return a special shap of array value by you given.
print("n's matrix\n",full)

random = np.random.random((2,3))
#return a matix of random value and shap you provide like (2,3)
print(random)

randomInt = np.random.randint((1,10))
print(randomInt)

sequence = np.arange(1,10,2)
print('sequence array:\n',sequence)

zero's array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1's matrix
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
n's matrix
 [[5 5]
 [5 5]
 [5 5]]
[[0.94079506 0.09958001 0.7913708 ]
 [0.35166554 0.20595587 0.47105358]]
[0 6]
sequence array:
 [1 3 5 7 9]


### Property of array

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])

print('Shape',arr.shape) #get shape of array
print('Size',arr.size) #get size of array //how much element in
print('Dimension',arr.ndim)  #get dimension of array
print('DataType',arr.dtype) #get datatype of array
#if any value is float it return float64 ,all is int =>int32, even one is string => <U11


Shape (2, 3)
Size 6
Dimension 2
DataType int32


## Vector Metrix Tensor

In [ ]:
vector = np.array([1,2,3,4,5,6])
print('Vector: ',vector)


matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print('Matrix',matrix)

tensor = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print("Tensor: ",tensor)

Vector:  [1 2 3 4 5 6]
Matrix [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3


### Array Reshaping

In [ ]:
arry = np.arange(12)
print('Original Array: ',arry)

reshaped = arry.reshape(3,4)
print('Reshaped array: ',reshaped) #it reshap the array with given shap

flatten = reshaped.flatten() #flat the array , it return a copy
print(flatten)

raveled = reshaped.ravel()  #it also flat the array //difference with this it return view , instead of copy means it give original array
print('Raveled array: ',raveled)

transposed = reshaped.T
print('Transposed of arr :\n',transposed) #return a transposed of arry
#transposed means turn row in to colmn and colmn to row 

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed of arr :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
